name: Deploy lm-listener
on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get branch name
        id: branch
        run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT

      - name: Deploy develop branch
        if: steps.branch.outputs.branch == 'develop'
        uses: appleboy/ssh-action@master
        with:
          host: login.isca.ex.ac.uk
          username: xk219
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /lustre/projects/Research_Project-T127204/xk219/projects/github_code/lm-listener
            git pull origin develop
